AccreditGitHubUsers/Models/GithubProfile.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AccreditGitHubUsers.Models
{
    public class GithubProfile
    {
        public int Id { get; set; }

        [Display(Name = "Username")]
        public string Login { get; set; }

        [DisplayFormat(NullDisplayText = "Unknown Name")]
        public string Name { get; set; }

        public string Avatar_Url { get; set; }

        [DisplayFormat(NullDisplayText = "Unknown Location")]
        public string Location { get; set; }

        public string Repos_Url { get; set; }

        public ICollection<GithubProject> AllProjects { get; set; }
    }
}

AccreditGitHubUsers/Controllers/GithubProfileController.cs
using AccreditGitHubUsers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace AccreditGitHubUsers.Controllers
{
    public class GithubProfileController : Controller
    {

        // PROPERTIES
        public GithubProfile GithubUser { get; set; }

        // CONSTRUCTOR
        public GithubProfileController()
        {

        }

        // ACTIONS
        public ActionResult Index()
        {
            // call Web API Controller from here
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44314/api/");

                //HTTP GET
              var responseTask = client.GetAsync("GithubProfileApi"); // calls the WEB API controller
                responseTask.Wait();

                var result = responseTask.Result;

                // check if Web API data fetch is successful
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<GithubProfile>();
                    readTask.Wait();

                    GithubUser = readTask.Result;
                }
                else //web api sent error response 
                {

                    GithubUser = null;

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }

            return View(GithubUser);
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            // call Web API Controller from here using the Search String
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44314/api/");

                //HTTP GET
                var responseTask = client.GetAsync("GithubProfileApi/" + search); // calls the WEB API controller
                responseTask.Wait();

                var result = responseTask.Result;

                // check if Web API data fetch is successful
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<GithubProfile>();
                    readTask.Wait();

                    GithubUser = readTask.Result;

                }
                else //web api sent error response 
                {

                    GithubUser = null;

                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator.");
                }
            }

            return View(GithubUser);
        }

       
    }
}

AccreditGitHubUsers/Controllers/GithubProjectsController.cs
using AccreditGitHubUsers.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web.Mvc;

namespace AccreditGitHubUsers.Controllers
{
    public class GithubProjectsController : Controller
    {

        // PROPERTIES
        public GithubProfile GithubUser { get; set; }

        // CONSTRUCTOR
        public GithubProjectsController()
        {
            
        }
        // is the controller getting the object from ActionLink or Index???
        // ACTIONS
        public ActionResult Index(GithubProfile githubUser)
        {

            // use the GithubProfile object from the Profile page
            GithubUser = githubUser;
            githubUser.AllProjects = new List<GithubProject>();

            // call Web API Controller from here using the Search String
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44314/api/");

                //HTTP GET
                var responseTask = client.GetAsync("GithubProjectsApi/" + GithubUser.Login); // calls the WEB API controller
                responseTask.Wait();

                var result = responseTask.Result;

                // check if Web API data fetch is successful
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<GithubProject>>();
                    readTask.Wait();

                    if (readTask.Result.Count != 0) {

                        GithubUser.AllProjects = readTask.Result.OrderByDescending(x => x.Stargazers_Count).Take(5).ToList();

                    }

                }
                else //web api sent error response 
                {

                    GithubUser.AllProjects = (ICollection<GithubProject>)Enumerable.Empty<GithubProject>(); ; // empty the list

                    ModelState.AddModelError(string.Empty, "Server error.");
                }
            }

            return View(GithubUser);
        }

       
    }
}

AccreditGitHubUsers/Views/GithubProfile/Index.cshtml
@model AccreditGitHubUsers.Models.GithubProfile

@{
    ViewBag.Title = "Home";
}

<h2>Search for a Github user</h2>

<!-- Search Form Without JQuery -->
<div class="flex-row">
    <div class="col-10 search_bar">
        @using (Html.BeginForm("Index", "GithubProfile", FormMethod.Post))
    {
        <span>Github UserName:</span>  @Html.TextBox("search")
        <input class="btn btn-primary" type="submit" value="search" />
    }
    </div>
</div>


@if (Model == null)
{
    <div class="flex-row justify-content-center">
        <div class="col">
            <p style="color:darkred">No Github User found! Please ensure the name is correct!</p>
        </div>
    </div>
}
else {

        <table class="table" id="user_table">
            <tr>
                <th>
                    Avatar Image
                </th>
                <th>
                    Username
                </th>
                <th>
                    Location
                </th>
                <th>
                    View Profile
                </th>
            </tr>


            <tr class="table_row">
                <td>
                    <img src="@Html.DisplayFor(model => model.Avatar_Url)" alt="Avatar_Image" class="avatar_image"/>
                </td>
                <td>
                    @Html.DisplayFor(model => model.Login)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Location)
                </td>
                <td>
                    @Html.ActionLink("Projects", "Index", "GithubProjects", Model, null)
                </td>
            </tr>

        </table>

}


<div class="flex-row" style="margin-top: 20px;">
    <p>Test 1 (Valid Username with Projects): <span style="font-weight: bold;">robconery</span></p>
    <p>Test 2 (Invalid Username): <span style="font-weight: bold;">robconer</span></p>
    <p>Test 3 (Valid Username with no Projects): <span style="font-weight: bold;">techyay</span></p>
</div>

<div class="flex-row" style="margin-top: 40px;">
    <p><span style="font-weight: bold;">Note:</span> You need to type the full UserName for the GitHub user in order to find a User. (Partial names dont return a list of possible results)</p>
</div>